name: Build and push container

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/obeone/rss-watcher:latest
            obeoneorg/rss-watcher:latest

      - name: Set up cosign
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@v3

      - name: Sign the container image with cosign
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cosign sign --yes ghcr.io/obeone/rss-watcher@${DIGEST}
          cosign sign --yes docker.io/obeoneorg/rss-watcher@${DIGEST}
        env:
          COSIGN_EXPERIMENTAL: true
          DIGEST: ${{ steps.docker_build.outputs.digest }}

      - name: Update Docker Hub description
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: obeoneorg/rss-watcher
